local_cache_root = "/Users/aktech/.cache/ragna"
document = "ragna.core.LocalDocument"
authentication = "ragna.deploy._authentication.RagnaDemoAuthentication"

[components]
source_storages = ["ragna.source_storages.RagnaDemoSourceStorage"]
assistants = ["ragna.assistants.RagnaDemoAssistant"]

[api]
url = "http://127.0.0.1:31476"
origins = ["http://127.0.0.1:31476"]
database_url = "sqlite:////Users/aktech/.cache/ragna/ragna.db"
root_path = "/user/aktech/ragna-api-f8ed40f/"

[ui]
url = "http://127.0.0.1:31477"
origins = ["http://127.0.0.1:31477"]
