local_cache_root = "/Users/aktech/.cache/ragna"
document = "ragna.core.LocalDocument"
authentication = "ragna.deploy._authentication.RagnaDemoAuthentication"

[components]
source_storages = ["ragna.source_storages.RagnaDemoSourceStorage"]
assistants = ["ragna.assistants.RagnaDemoAssistant"]

[api]
url = "http://127.0.0.1:8000"
origins = ["http://127.0.0.1:8000"]
database_url = "memory"
root_path = "/user/aktech/ragna-api-3c98e2b/"

[ui]
url = "http://127.0.0.1:31477"
origins = ["http://127.0.0.1:31477"]
