name: Package

on:
  push:
jobs:
  package:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: mamba-org/setup-micromamba@v1.4.3
        with:
          init-shell: bash
          environment-name: package
          create-args: >-
            python=${{ matrix.python-version }}
            mamba

      - name: Install conda constructor
        run: mamba install constructor
        shell: micromamba-shell {0}

      - name: Package Japps
        run: constructor .
        shell: micromamba-shell {0}
