name: Package

on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: mamba-org/setup-micromamba@v1.4.3
      with:
        python-version: ${{ matrix.python-version }}
        environment-file: environment-dev.yml
        create-args: >-
          python=${{ matrix.python-version }}

    - name: Install conda constructor
      run: conda install constructor

    - name: Package Japps
      run: constructor .
